<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$display = !$objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
    ->getValue('magefan_customerdataprotectionondev/data/deleted');
?>

<?php if ($display) { ?>
<div id="messages">
    <div class="messages">
        <div class="message message-error error">
            <div data-ui-id="messages-message-error">
                Please <a href="<?= $block->escapeUrl($block->getUrl('magefan_customerdataprotectionondev/delete/edit')) ?>">remove customer data</a> from dev instance. If it is live instance disable Magefan_CustomerDataProtectionOnDev module.
            </div>
        </div>
    </div>
</div>
<?php } ?>